import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart' show debugPrint, kIsWeb;

import '../../core/constants/app_constants.dart';
import '../storage/storage_paths.dart';
import 'retry_interceptor.dart';

/// Fetches distributed market snapshot files generated by the serverless
/// pipeline and caches them on disk under
/// `<AppDocs>/PortfolioManager/cache/market/` so the app can render the
/// last known state while offline.
class MarketSnapshotService {
  static const String _topMoversFileName = 'top_movers.json';
  static const String _pricesIndexFileName = 'prices_index.json';

  /// Weight of top_movers.json in the combined refresh progress (0..1).
  /// Top movers is small (a few hundred KB), prices_index is much larger
  /// (often >5 MB), so we give the prices index the bulk of the bar.
  static const double _topMoversProgressWeight = 0.30;
  static const double _pricesIndexProgressWeight = 0.70;

  final Dio _dio;

  static const Set<String> _exchangeSuffixes = <String>{
    'US',
    'USA',
    'NASDAQ',
    'NYSE',
    'AMEX',
    'BATS',
    'OTC',
    'OTCBB',
    'LSE',
    'LON',
    'XETRA',
    'FRA',
    'FSE',
    'PA',
    'EPA',
    'EURONEXT',
    'TO',
    'TSX',
    'TSXV',
    'HK',
    'HKG',
    'AU',
    'AX',
    'ASX',
    'NSE',
    'BSE',
  };

  /// In-memory cache for prices_index to avoid repeated downloads in a session.
  Map<String, dynamic>? _cachedPricesIndex;
  DateTime? _pricesIndexCachedAt;
  static const Duration _pricesIndexCacheTtl = Duration(hours: 4);

  MarketSnapshotService({Dio? dio}) : _dio = dio ?? Dio() {
    _dio.options.connectTimeout = AppConstants.apiTimeout;
    _dio.options.receiveTimeout = AppConstants.apiTimeout;
    _dio.options.sendTimeout = AppConstants.apiTimeout;
    _dio.interceptors.add(RetryInterceptor(dio: _dio));
  }

  bool get isConfigured => AppConstants.marketSnapshotBaseUrl.trim().isNotEmpty;

  String get _baseUrl {
    final url = AppConstants.marketSnapshotBaseUrl.trim();
    return url.endsWith('/') ? url.substring(0, url.length - 1) : url;
  }

  Future<Map<String, dynamic>?> fetchTopMoversSnapshot({
    void Function(double progress)? onProgress,
  }) async {
    if (!isConfigured) return null;
    try {
      final response = await _dio.get(
        '$_baseUrl/top_movers.json',
        onReceiveProgress: onProgress == null
            ? null
            : (received, total) {
                if (total <= 0) return;
                final ratio = (received / total).clamp(0.0, 1.0);
                onProgress(ratio);
              },
      );
      final payload = response.data;
      if (payload is! Map) return null;
      final map = Map<String, dynamic>.from(payload);
      // Persist fresh copy -- best-effort, failures must not fail the fetch.
      unawaited(_writeJsonToCache(_topMoversFileName, map));
      return map;
    } catch (_) {
      // Fall back to the on-disk copy if available, otherwise rethrow
      // the behaviour of returning null to stay compatible with callers.
      final cached = await loadCachedTopMovers();
      return cached;
    }
  }

  /// Refreshes both distributed snapshots (top_movers + prices_index) in
  /// sequence, reporting an aggregated progress in [0.0, 1.0] through
  /// [onProgress]. Failures of either download are absorbed -- the method
  /// returns true only if at least one snapshot was successfully fetched.
  ///
  /// This is the entry point used by the splash screen on app start so the
  /// user sees a visible loading bar while the day's data is pulled from
  /// GitHub Pages.
  Future<bool> refreshAll({
    void Function(double progress)? onProgress,
  }) async {
    if (!isConfigured) {
      onProgress?.call(1.0);
      return false;
    }

    onProgress?.call(0.0);

    bool anySuccess = false;

    try {
      final movers = await fetchTopMoversSnapshot(
        onProgress: onProgress == null
            ? null
            : (ratio) => onProgress(ratio * _topMoversProgressWeight),
      );
      if (movers != null) {
        anySuccess = true;
      }
    } catch (error, stack) {
      debugPrint('MarketSnapshotService.refreshAll movers error: $error');
      debugPrint('$stack');
    }

    onProgress?.call(_topMoversProgressWeight);

    try {
      final prices = await fetchPricesIndex(
        forceRefresh: true,
        onProgress: onProgress == null
            ? null
            : (ratio) => onProgress(
                  _topMoversProgressWeight +
                      ratio * _pricesIndexProgressWeight,
                ),
      );
      if (prices != null) {
        anySuccess = true;
      }
    } catch (error, stack) {
      debugPrint('MarketSnapshotService.refreshAll prices error: $error');
      debugPrint('$stack');
    }

    onProgress?.call(1.0);
    return anySuccess;
  }

  /// Reads the last top_movers snapshot persisted on disk, if any.
  ///
  /// Returns null on web (the disk cache is disabled there) or when no
  /// snapshot has been downloaded yet.
  Future<Map<String, dynamic>?> loadCachedTopMovers() =>
      _readJsonFromCache(_topMoversFileName);

  /// Reads the last prices_index snapshot persisted on disk, if any.
  Future<Map<String, dynamic>?> loadCachedPricesIndex() =>
      _readJsonFromCache(_pricesIndexFileName);

  /// Downloads and caches the prices_index.json snapshot.
  ///
  /// Returns a map keyed by ``MARKET:TICKER`` and ``TICKER`` (flat) with
  /// compact price entries: {c: close, cu: currency, m: market, d: date}.
  Future<Map<String, dynamic>?> fetchPricesIndex({
    bool forceRefresh = false,
    void Function(double progress)? onProgress,
  }) async {
    if (!isConfigured) return null;

    final now = DateTime.now();
    if (!forceRefresh &&
        _cachedPricesIndex != null &&
        _pricesIndexCachedAt != null &&
        now.difference(_pricesIndexCachedAt!) < _pricesIndexCacheTtl) {
      onProgress?.call(1.0);
      return _cachedPricesIndex;
    }

    try {
      final response = await _dio.get(
        '$_baseUrl/prices_index.json',
        onReceiveProgress: onProgress == null
            ? null
            : (received, total) {
                if (total <= 0) return;
                final ratio = (received / total).clamp(0.0, 1.0);
                onProgress(ratio);
              },
      );
      final payload = response.data;
      if (payload is! Map) return null;

      final map = Map<String, dynamic>.from(payload);
      final prices = map['prices'];
      if (prices is! Map) return null;

      // Persist the full payload (wrapper + prices) so the on-disk copy
      // keeps the same shape as the network response and survives
      // across restarts.
      unawaited(_writeJsonToCache(_pricesIndexFileName, map));

      _cachedPricesIndex = Map<String, dynamic>.from(prices);
      _pricesIndexCachedAt = now;
      return _cachedPricesIndex;
    } catch (_) {
      // Network failure: try the on-disk copy as a last-resort fallback.
      final cached = await loadCachedPricesIndex();
      if (cached == null) return null;
      final prices = cached['prices'];
      if (prices is! Map) return null;
      _cachedPricesIndex = Map<String, dynamic>.from(prices);
      _pricesIndexCachedAt = now;
      return _cachedPricesIndex;
    }
  }

  // ==================== Disk cache helpers ====================

  Future<File?> _cacheFile(String name) async {
    if (kIsWeb) return null;
    if (!StoragePaths.isReady) return null;
    return File(
      '${StoragePaths.marketCacheDir}${Platform.pathSeparator}$name',
    );
  }

  Future<void> _writeJsonToCache(String name, Map<String, dynamic> data) async {
    try {
      final file = await _cacheFile(name);
      if (file == null) return;
      await file.writeAsString(jsonEncode(data), flush: true);
    } catch (error, stack) {
      // Disk cache is an optimization; do not fail the fetch, but make
      // the error visible in debug builds so corrupted writes can be
      // spotted during development.
      debugPrint('MarketSnapshotService: failed to cache $name -> $error');
      debugPrint('$stack');
    }
  }

  Future<Map<String, dynamic>?> _readJsonFromCache(String name) async {
    try {
      final file = await _cacheFile(name);
      if (file == null) return null;
      if (!await file.exists()) return null;
      final raw = await file.readAsString();
      if (raw.trim().isEmpty) return null;
      final decoded = jsonDecode(raw);
      if (decoded is! Map) return null;
      return Map<String, dynamic>.from(decoded);
    } catch (_) {
      return null;
    }
  }

  /// Looks up a snapshot price for [ticker] (optionally with [marketCode]).
  ///
  /// Lookup order: ``{MARKET}:{TICKER}`` -> flat ``{TICKER}``.
  /// Returns ``{c, cu, m, d}`` or null if not found.
  ///
  /// It also normalizes common broker symbol formats (e.g. ``AAPL.US``,
  /// ``BRK.B``) to reduce false "price not found" cases.
  Map<String, dynamic>? lookupPrice(
    Map<String, dynamic> pricesIndex, {
    required String ticker,
    String? marketCode,
  }) {
    final candidates = _buildTickerCandidates(ticker);
    if (candidates.isEmpty) {
      return null;
    }

    final normalizedMarket = marketCode?.trim().toUpperCase();
    if (normalizedMarket != null && normalizedMarket.isNotEmpty) {
      for (final candidate in candidates) {
        final mk = '$normalizedMarket:$candidate';
        final entry = pricesIndex[mk];
        if (entry is Map) return Map<String, dynamic>.from(entry);
      }
    }

    for (final candidate in candidates) {
      final flat = pricesIndex[candidate];
      if (flat is Map) return Map<String, dynamic>.from(flat);
    }

    return null;
  }

  /// Normalizes a symbol used by broker imports/API inputs into snapshot format.
  String normalizeTicker(String ticker) {
    final candidates = _buildTickerCandidates(ticker);
    return candidates.isEmpty ? '' : candidates.first;
  }

  List<String> _buildTickerCandidates(String ticker) {
    final raw = ticker.trim().toUpperCase().replaceAll(' ', '');
    if (raw.isEmpty) {
      return const <String>[];
    }

    final candidates = <String>{raw};

    final stripped = _stripExchangeSuffix(raw);
    if (stripped != null && stripped.isNotEmpty) {
      candidates.add(stripped);
    }

    final toInspect = <String>{...candidates};
    for (final value in toInspect) {
      final classMatch =
          RegExp(r'^([A-Z0-9]+)[./-]([A-Z0-9]{1,2})$').firstMatch(value);
      if (classMatch != null) {
        final base = classMatch.group(1)!;
        final shareClass = classMatch.group(2)!;
        candidates.add('$base-$shareClass');
        candidates.add('$base.$shareClass');
        candidates.add('$base/$shareClass');
      }

      if (value.contains('.')) {
        candidates.add(value.replaceAll('.', '-'));
      }
      if (value.contains('/')) {
        candidates.add(value.replaceAll('/', '-'));
      }
    }

    return candidates.toList(growable: false);
  }

  String? _stripExchangeSuffix(String ticker) {
    for (final separator in const ['.', ':', '/', '-']) {
      final idx = ticker.lastIndexOf(separator);
      if (idx <= 0 || idx >= ticker.length - 1) {
        continue;
      }
      final suffix = ticker.substring(idx + 1);
      if (_exchangeSuffixes.contains(suffix)) {
        return ticker.substring(0, idx);
      }
    }
    return null;
  }

  void clearPricesIndexCache() {
    _cachedPricesIndex = null;
    _pricesIndexCachedAt = null;
  }
}
